### ISSUE TITLE
Is there any order to be followed to approach these exercises?

### ISSUE THREAD

**Issue by segmentationfaulter** [kolodny/exercises#36]
I am new to JavaScript, I was wondering if there is any order to be followed to approach these exercises?  Moreover, what do you suggest for a beginner javascripter, should he/she attempt these exercises?

**Comment by kolodny** [comment]
There's no official order, there is an issue to make some levels though #16 

I would quickly rank them as:
1. map, value, once
2. curry, memoize
3. binary-search, flatten, invert-tree
4. sort, flatten-thunk
5. debounce, jasmine-async, middleware
6. throttle-promises, morse-code, async, merkle.

**Comment by segmentationfaulter** [comment]
Thank you @kolodny , it will be a lot of help for a beginner like me.
